// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fivhqsngwgsfdjxlojae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpdmhxc25nd2dzZmRqeGxvamFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTEyMjYsImV4cCI6MjA3MzY2NzIyNn0.kbyT5HzAUC4SfKn6dNCbezretJpUcIryp7Z5iNlMYE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});